
# Тема 10.Декораторы и исключения  
Отчет по Теме #10 выполнил:
- Погребняк Кирилл Федорович
- ИНО ОЗБ ПОАС 22-2

| Задание  | Сам_раб |
| ------ | ------ |
| Задание 1 | + | 
| Задание 2 | + | 
| Задание 3 | + | 
| Задание 4 | + | 
| Задание 5 | + | 



знак "+" - задание выполнено; знак "-" - задание не выполнено;

Работу проверили:
- к.э.н., доцент Панов М.А.

## Самостоятельная работа №10
### 1)Вовочка решил заняться спортивным программированием на python, но
для этого он должен знать за какое время выполняется его программа.
Он решил, что для этого ему идеально подойдет декоратор для
функции, который будет выяснять за какое время выполняется та или
иная функция. Помогите Вовочке в его начинаниях и напишите такой
декоратор.
Подсказка: необходимо использовать модуль time
Декоратор необходимо использовать для этой функции
Результатом вашей работы будет листинг кода и скриншот консоли, в
котором будет ыполненная функция Фибоначчи и время выполнения
программы.
Также на том примере можете посмотреть, что решение задач через
рекур ию не всегда является хорошей идеей. Поскольку решение
Фи оначчи для 100 с использованием рекурсии и без динамического
программирования решается более десяти секунд, а решение точно
такой же задачи, но через цикл for еще и для 200, занимает меньше 1
секунды



```python
import time
def timing_decorator(func):
    def wrapper(*args, **kwargs):
        start_time = time.perf_counter()
        result = func(*args, **kwargs)
        end_time = time.perf_counter()
        elapsed_time = end_time - start_time
        print(f"Функция {func.__name__} выполнена за {elapsed_time:.6f} секунд")
        return result
    return wrapper

@timing_decorator
def calculate_sum(n):
    return sum(range(1, n + 1))

print(calculate_sum(1000000))

```
### Результат.
![Меню](https://github.com/Fedorovich96/Software/blob/%D0%A2%D0%B5%D0%BC%D0%B0_10/pic/10-1.png)

### 2)Посмотрев на Вовочку, вы также загорелись идеей спортивного
программирования, начав тренировки вы узнали, что для решения
некоторых задач необходимо считывать данные из файлов. Но через
некоторое время вы столкнулись с проблемой что файлы бывают
пустыми, и вы не получаете вводные данные для решения задачи.
После этого вы решили не просто считывать данные из файла, а всю
конструкцию оборачивать в исключения, чтобы избежать такой
проблемы. Создайте пустой файл и файл, в котором есть какая-то
информация. Напишите код программы. Если файл пустой, то, нужно
вызвать исключение (“бросить исключение”) и вывести в консоль
“
файл пустой”, а если он не пустой, то вывести информацию из файла.



```python
def read_file_content(filename):
    try:
        with open(filename, 'r') as file:
            content = file.read().strip()
            if not content:
                raise ValueError("файл пустой")
            return content
    except FileNotFoundError:
        print(f"Файл {filename} не найден.")
    except ValueError as e:
        print(e)

with open('empty_file.txt', 'w') as file:
    pass

with open('non_empty_file.txt', 'w') as file:
    file.write("Привет, мир!")

print(read_file_content('empty_file.txt'))

print(read_file_content('non_empty_file.txt'))
```
### Результат.
![Меню](https://github.com/Fedorovich96/Software/blob/%D0%A2%D0%B5%D0%BC%D0%B0_10/pic/10-2.png)

### 3)Напишите функцию, которая будет складывать 2 и введенное
пользователем число, но если пользователь введет строку или другой
неподходящий тип данных, то в консоль выведется ошибка
“
Неподходящий тип данных. Ожидалось число.”. Реализовать
функционал программы необходимо через try/except и подоб
правильный тип исключения. Создавать собственное исключ
ь
нельзя. Проведите несколько тестов, в которых исключ
и нет. Результатом выполнения задачи будет листинг ко
получившийся вывод в консоль


```python
def add_two_and_user_input():
    try:
        user_input = input("Введите число: ")
        number = float(user_input)
        result = 2 + number
        print(f"Результат сложения  {result}")
    except ValueError:
        print("Неподходящий тип данных. Ожидалось число.")

add_two_and_user_input()
add_two_and_user_input()
add_two_and_user_input()


```
### Результат.
![Меню](https://github.com/Fedorovich96/Software/blob/%D0%A2%D0%B5%D0%BC%D0%B0_10/pic/10-3.png)

### 4)Создайте собственный декоратор, кото ый удет использоваться для
двух любых вами придуманных функци . Декораторы, которые
использовались ранее в работе нельзя вос оздавать. Результатом
выполнения задачи будет: класс декоратора, две как-то связанными с
ним функциями, скриншот ко
и с выполненной программой и
подробные комментарии, кото ые будут описывать работу вашего
кода.


```python

class LoggingDecorator:
    def __init__(self, func):
        self.func = func

    def __call__(self, *args, **kwargs):
        print(" Выполняется функция:", self.func.__name__)
        result = self.func(*args, **kwargs)
        print(" Функция выполнена:", self.func.__name__)
        return result


@LoggingDecorator
def add(a, b):
    return a + b


@LoggingDecorator
def subtract(a, b):
    return a - b


result_add = add(5, 3)
print("Результат сложения:", result_add)

result_subtract = subtract(10, 4)
print("Результат вычитания:", result_subtract)


```
### Результат.
![Меню](https://github.com/Fedorovich96/Software/blob/%D0%A2%D0%B5%D0%BC%D0%B0_10/pic/10-4.png)

### 5)Создайте собств нное исключение, которое будет использоваться в
двух любых фраг ентах кода. Исключения, которые использовались
ранее в работе льзя воссоздавать. Результатом выполнения задачи
будет: кл сс исключения, код к котором в двух местах используется это
исключе ие, скриншот консоли с выполненной программой и
подро ные комментарии, которые будут описывать работу вашего
код .


```python
class MyCustomException(Exception):
    def __init__(self, message="Это мое собственное исключение!"):
        self.message = message
        super().__init__(self.message)

# Фрагмент кода 1: Где исключение будет создаваться
def divide_numbers(a, b):
    if b == 0:
        raise MyCustomException("Попытка деления на ноль!")
    return a / b

try:
    result = divide_numbers(10, 0)
except MyCustomException as e:
    print(f"Произошло исключение: {e}")

# Фрагмент кода 2: Где исключение будет обработано
try:
    number = int(input("Введите число больше 10: "))
    if number <= 10:
        raise MyCustomException("Введено число меньше или равное 10!")
except MyCustomException as e:
    print(f"Произошло исключение: {e}")

```
### Результат.
![Меню](https://github.com/Fedorovich96/Software/blob/%D0%A2%D0%B5%D0%BC%D0%B0_10/pic/10-5.png)

